### ISSUE TITLE
How to post on my linkedin acount.

### ISSUE THREAD

**Issue by Ujjaval91** [sajari/simple-linkedin-php#3]
Hello,

I need to post article/post using this library.
I have installed it by the composer.
Please suggest how to use/call the function to share a post.

Also, i have tried with almost same example, where i got an error like "Exception class not found".
I checked in your code and found that you also have extended the "Exception" class "**class LinkedInException extends Exception {}**" but I can not found the class in your library.

Kindly assist.

**Comment by mish15** [comment]
@Ujjaval91 would love to help, but our API access got cutoff, we don't know why as no one would respond to us. Feel free to modify this code as you wish, it's getting pretty old now.

**Comment by Ujjaval91** [comment]
OK no problem.

I just want to know to that from where i can get the "Exception" class to extends child class.

Please suggest.
